

export const ConfigKey = {
    JWT_SECRET: 'JWT_SECRET',
    JWT_EXPIRE_TIME: 'JWT_EXPIRE_TIME',
    DB_HOST: 'DB_HOST',
    DB_USER: 'DB_USER',
    DB_PASSWORD: 'DB_PASSWORD',
    DB_DATABASE: 'DB_DATABASE',
    DB_NAME: 'DB_NAME',
    DB_PORT: 'DB_PORT',
    DB_SYNC: 'DB_SYNC',
    REDIS_HOST: 'REDIS_HOST',
    REDIS_PORT: 'REDIS_PORT',
    REDIS_URL: 'REDIS_URL',
};

export const MessageConstant = {
    PASSWORD_ERROR: '密码错误',
    USER_NOT_EXIST: '用户不存在',
    CODE_ERROR: '验证码错误',
    ILLEGAL_VALUE: '非法值',
    SUCCESS: '成功',
    USER_DISABLED: '用户被禁用',
    USER_ALREADY_EXIST: '用户已存在',
    USER_NOT_LOGIN: '用户未登录',
    USERNAME_ALREADY_EXIST: '用户名已存在',
    EMAIL_ALREADY_EXIST: '邮箱已存在',
    PHONE_ALREADY_EXIST: '手机号已存在',
    VERIFY_CODE_SEND_SUCCESS: '验证码发送成功',
    USER_CONTENT_NOT_FOUND: '用户内容不存在',
    USER_CONTENT_ALREADY_EXIST: '用户内容已存在',
    USER_CONTENT_NOT_OWNER: '不是该用户内容的拥有者',
    USER_CONTENT_NOT_APPROVED: '用户内容未通过审核',
    USER_CONTENT_NOT_PUBLIC: '用户内容未公开',
    USER_NOT_ADMIN: '不是管理员',
    USER_NOT_MODERATOR: '不是版主',
    USER_NOT_APPROVED: '用户未通过审核',
    USER_NOT_PUBLIC: '用户未公开',
    USER_NOT_SUPER_ADMIN: '不是超级管理员',
    TOPIC_NOT_FOUND: '话题不存在',
    TOPIC_ALREADY_EXIST: '话题已存在',
    TOPIC_NOT_OWNER: '不是该话题的拥有者',
    TOPIC_NOT_APPROVED: '话题未通过审核',
    TOPIC_NOT_PUBLIC: '话题未公开',
    COMMENT_NOT_FOUND: '评论不存在',
    COMMENT_ALREADY_EXIST: '评论已存在',
    COMMENT_NOT_OWNER: '不是该评论的拥有者',
    COMMENT_NOT_APPROVED: '评论未通过审核',
    COMMENT_NOT_PUBLIC: '评论未公开',
    LIKE_ALREADY_EXIST: '已点赞',
    REWARD_NOT_FOUND: '奖励不存在',
    REWARD_ALREADY_EXIST: '奖励已存在',
    REWARD_NOT_OWNER: '不是该奖励的拥有者',
    REWARD_NOT_APPROVED: '奖励未通过审核',
    ROLE_NOT_EXIST: '角色不存在',
    ROLE_ALREADY_EXIST: '角色已存在',
    GAME_NOT_EXIST: '游戏不存在',
    GAME_ALREADY_EXIST: '游戏已存在',
    INTERACTION_NOT_FOUND: '互动不存在',
    INTERACTION_ALREADY_EXIST: '互动已存在',
    INTERACTION_NOT_OWNER: '不是该互动的拥有者',
    INTERACTION_NOT_APPROVED: '互动未通过审核',
    INTERACTION_NOT_PUBLIC: '互动未公开',
    MFA_SETTING_NOT_FOUND: 'MFA设置不存在',
    MFA_SETTING_ALREADY_EXIST: 'MFA设置已存在',
    MFA_SETTING_NOT_OWNER: '不是该MFA设置的拥有者',
    MFA_SETTING_NOT_APPROVED: 'MFA设置未通过审核',
    MFA_SETTING_NOT_PUBLIC: 'MFA设置未公开',
    NOTIFICATION_NOT_FOUND: '通知不存在',
    NOTIFICATION_ALREADY_EXIST: '通知已存在',
    NOTIFICATION_NOT_OWNER: '不是该通知的拥有者',
    NOTIFICATION_NOT_APPROVED: '通知未通过审核',
    NOTIFICATION_NOT_PUBLIC: '通知未公开',
    PERMISSION_NOT_FOUND: '权限不存在',
    PERMISSION_ALREADY_EXIST: '权限已存在',
    RESOURCE_NOT_FOUND: '资源不存在',
    RESOURCE_ALREADY_EXIST: '资源已存在',
    RESOURCE_NOT_OWNER: '不是该资源的拥有者',
    RESOURCE_NOT_APPROVED: '资源未通过审核',
    RESOURCE_NOT_PUBLIC: '资源未公开',
    ROLE_NOT_OWNER: '不是该角色的拥有者',
    ROLE_NOT_APPROVED: '角色未通过审核',
    ROLE_NOT_PUBLIC: '角色未公开',
    SUPPORT_TICKET_NOT_FOUND: '支持工单不存在',
    SUPPORT_TICKET_ALREADY_EXIST: '支持工单已存在',
    SUPPORT_TICKET_NOT_OWNER: '不是该支持工单的拥有者',
    SUPPORT_TICKET_NOT_APPROVED: '支持工单未通过审核',
    SUPPORT_TICKET_NOT_PUBLIC: '支持工单未公开',
    TASK_REWARD_NOT_FOUND: '任务奖励不存在',
    TASK_REWARD_ALREADY_EXIST: '任务奖励已存在',
    TASK_REWARD_NOT_OWNER: '不是该任务奖励的拥有者',
    TASK_REWARD_NOT_APPROVED: '任务奖励未通过审核',
    TASK_REWARD_NOT_PUBLIC: '任务奖励未公开',
    COLLECT_ALREADY_EXIST: '已收藏',
    ADMIN_CAN_NOT_DELETE_SELF: '管理员不能删除自己',
    ADMIN_CAN_NOT_CHANGE_SELF_STATUS: '管理员不能修改自己的状态',
    COMMUNITY_NOT_FOUND: '社区不存在',
    COMMUNITY_ALREADY_EXIST: '社区已存在',
    COMMUNITY_NOT_OWNER: '不是该社区的拥有者',
    COMMUNITY_NOT_ADMIN: '不是社区管理员',
    COMMUNITY_NOT_MODERATOR: '不是社区版主',
    COMMUNITY_NOT_APPROVED: '社区未通过审核',
    COMMUNITY_NOT_PUBLIC: '社区未公开',
    COMMUNITY_NOT_ACTIVE: '社区未激活',
    COMMUNITY_NOT_DELETED: '社区未删除',
    COMMUNITY_NOT_BANNED: '用户已被禁言',
    COMMUNITY_BANNED_ALREADY_EXIST: '用户已被禁言',
    COMMUNITY_BANNED_NOT_FOUND: '用户未被禁言',
    COMMUNITY_BANNED_NOT_OWNER: '不是该用户的禁言记录的拥有者',
    COMMUNITY_BANNED_NOT_APPROVED: '用户禁言记录未通过审核',
    COMMUNITY_BANNED_NOT_PUBLIC: '用户禁言记录未公开',
    COMMUNITY_BANNED_NOT_ACTIVE: '用户禁言记录未激活',
    COMMUNITY_BANNED_NOT_DELETED: '用户禁言记录未删除',
    COMMUNITY_BANNED_NOT_BANNED: '用户已被禁言',
    COMMUNITY_BANNED_ALREADY_BANNED: '用户已被禁言',
    COMMUNITY_BANNED_EXPIRED: '用户禁言记录已过期',
    COMMUNITY_BANNED_ALREADY_EXPIRED: '用户禁言记录已过期',
    COMMUNITY_BANNED_NOT_EXPIRED: '用户禁言记录未过期',
    COMMUNITY_BANNED_EXPIRE_TIME_NOT_FOUND: '用户禁言记录过期时间未找到',
    COMMUNITY_BANNED_EXPIRE_TIME_ALREADY_EXIST: '用户禁言记录过期时间已存在',
    COMMUNITY_BANNED_EXPIRE_TIME_NOT_OWNER: '不是该用户禁言记录的过期时间的拥有者',
    USER_ALREADY_MOD: '用户已经是游戏的版主',
    USER_NOT_MOD: '用户不是游戏的版主',
    ADMIN_NOT_ALLOW_BECOME_MODERATOR:"管理员不能成为版主"
}

export enum AbilityAction {
    MANAGE = 'MANAGE',
    CREATE = 'CREATE',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
    READ = 'READ',
    COMMENT = 'COMMENT',
    DOWNLOAD = 'DOWNLOAD',
}
export enum AbilityResource {
    User='User',
    Comment='Comment',
    Feedback='Feedback',
    Game='Game',
    Interaction='Interaction',
    MfaSetting='MfaSetting',
    Notification='Notification',
    Permission='Permission',
    Resource='Resource',
    Role='Role',
    SupportTicket='SupportTicket',
    TaskReward='TaskReward',
    Topic='Topic',
    UserAuth='UserAuth',
    UserContent='UserContent',
    UserProfile='UserProfile',
    ALL='ALL',
}


export enum ExpPoint{
    EXP_POINT_UPLOAD_CONTENT = 10, // 上传内容
    EXP_POINT_COMMENT_CONTENT = 2, // 评论内容
    EXP_POINT_LOGIN = 10, // 登录
}

export const IS_PUBLIC_KEY = 'isPublic';
export const DEFAULT_AVATAR_URL = "https://gcpserver.oss-cn-chengdu.aliyuncs.com/avatar/default.png?x-oss-process=style/image-compress"